name: Tests

# Only test on Pull Requests that target main
on:
  pull_request:
    branches:
      - main
    paths: # Only run tests when certain paths change
      - fidesctl/**
      - .github/workflows/test.yaml

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker Images
        run: make compose-build

      - name: Check fidesctl installed
        run: make check-install

      - name: Format
        run: make black

      - name: Lint
        run: make pylint

      - name: TypeCheck
        run: make mypy

      - name: Complexity Check
        run: make xenon

      - name: Test
        run: make pytest

  Fidesctl:
    runs-on: ubuntu-latest
    container:
      image: ethyca/fidesctl:latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: fidesctl
          POSTGRES_PASSWORD: fidesctl
          POSTGRES_DATABASE: fidesctl
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432

      fidesctl:
        image: ethyca/fidesctl:latest
        options: --entrypoint /bin/bash "fidesctl webserver"
        env:
          FIDESCTL_CONFIG_PATH: fidesctl/fidesctl.toml

    steps:
      - uses: actions/checkout@v2

      - name: Dry Evaluation
        run: fidesctl evaluate --dry fidesctl/fides_resources/
        env:
          FIDESCTL_CONFIG_PATH: fidesctl/fidesctl.toml
